// /**
//  * Implement Gatsby's Browser APIs in this file.
//  *
//  * See: https://www.gatsbyjs.org/docs/browser-apis/
//  */

// const data = {
//   "header_content": {
//     "name": "header_content",
//     "label": "header_contents",
//     "singular_label": "header_content",
//     "description": "Header content data",
//     "public": "true",
//     "publicly_queryable": "true",
//     "show_ui": "true",
//     "show_in_graphql":"true",
//     "hierarchical": "true",
//     "graphql_single_name":"header_content",
//     "graphql_plural_name":"header_contents",
//     "show_in_nav_menus": "true",
//     "delete_with_user": "false",
//     "show_in_rest": "true",
//     "rest_base": "header_Page_Content",
//     "rest_controller_class": "",
//     "has_archive": "false",
//     "has_archive_string": "",
//     "exclude_from_search": "false",
//     "capability_type": "post",
//     "rewrite": "true",
//     "rewrite_slug": "",
//     "rewrite_withfront": "true",
//     "query_var": "true",
//     "query_var_slug": "",
//     "menu_position": "",
//     "show_in_menu": "true",
//     "show_in_menu_string": "",
//     "menu_icon": "dashicons-cloud",
//     "supports": [
//       "title",
//       "editor",
//       "thumbnail",
//       "excerpt",
//       "trackbacks",
//       "custom-fields",
//       "comments",
//       "revisions",
//       "author",
//       "page-attributes",
//       "post-formats",
//       "none"
//     ],
//     "taxonomies": ["category", "post_tag"],
//     "labels": {
//       "menu_name": "Header Page",
//       "all_items": "All Header Content",
//       "add_new": "Add New Header Content",
//       "add_new_item": "Add New Header Content",
//       "edit_item": "Edit Header Content",
//       "new_item": "New Header Content",
//       "view_item": "View Header Content",
//       "view_items": "View Header",
//       "search_items": "Search Header",
//       "not_found": "No Header Found",
//       "not_found_in_trash": "No Header Found In Trash",
//       "parent": "Parent Header Content",
//       "featured_image": "Featured Image For This Header Content",
//       "set_featured_image": "Set Featured Image For This Header Content",
//       "remove_featured_image": "Remove Featured Image For This Header Content",
//       "use_featured_image": "Use As Featured Image For This Header Content",
//       "archives": "Header Archive",
//       "insert_into_item": "Insert Into Header Page",
//       "uploaded_to_this_item": "Upload To The Header Page",
//       "filter_items_list": "Filter Header Page List",
//       "items_list_navigation": "Header List Navigation",
//       "items_list": "Header Content List",
//       "attributes": "Header Attributes",
//       "name_admin_bar": "Header Content",
//       "item_published": "Header Content Published",
//       "item_published_privately": "Header Content Published Privately",
//       "item_reverted_to_draft": "Header Content Reverted To Draft",
//       "item_scheduled": "Header Content Scheduled",
//       "item_updated": "Header Content Updated",
//       "parent_item_colon": "Parent Header Content"
//     },
//     "custom_supports": ""
//   },
//   "Home_content": {
//     "name": "Home_content",
//     "label": "Home_contents",
//     "singular_label": "Home_content",
//     "description": "Home content data",
//     "public": "true",
//     "publicly_queryable": "true",
//     "show_ui": "true",
//     "show_in_graphql":"true",
//     "hierarchical": "true",
//     "graphql_single_name":"Home_content",
//     "graphql_plural_name":"Home_contents",
//     "show_in_nav_menus": "true",
//     "delete_with_user": "false",
//     "show_in_rest": "true",
//     "rest_base": "Home_Page_Content",
//     "rest_controller_class": "",
//     "has_archive": "false",
//     "has_archive_string": "",
//     "exclude_from_search": "false",
//     "capability_type": "post",
//     "rewrite": "true",
//     "rewrite_slug": "",
//     "rewrite_withfront": "true",
//     "query_var": "true",
//     "query_var_slug": "",
//     "menu_position": "",
//     "show_in_menu": "true",
//     "show_in_menu_string": "",
//     "menu_icon": "dashicons-cloud",
//     "supports": [
//       "title",
//       "editor",
//       "thumbnail",
//       "excerpt",
//       "trackbacks",
//       "custom-fields",
//       "comments",
//       "revisions",
//       "author",
//       "page-attributes",
//       "post-formats",
//       "none"
//     ],
//     "taxonomies": ["category", "post_tag"],
//     "labels": {
//       "menu_name": "Home Page",
//       "all_items": "All Home Content",
//       "add_new": "Add New Home Content",
//       "add_new_item": "Add New Home Content",
//       "edit_item": "Edit Home Content",
//       "new_item": "New Home Content",
//       "view_item": "View Home Content",
//       "view_items": "View Home",
//       "search_items": "Search Home",
//       "not_found": "No Home Found",
//       "not_found_in_trash": "No Home Found In Trash",
//       "parent": "Parent Home Content",
//       "featured_image": "Featured Image For This Home Content",
//       "set_featured_image": "Set Featured Image For This Home Content",
//       "remove_featured_image": "Remove Featured Image For This Home Content",
//       "use_featured_image": "Use As Featured Image For This Home Content",
//       "archives": "Home Archive",
//       "insert_into_item": "Insert Into Home Page",
//       "uploaded_to_this_item": "Upload To The Home Page",
//       "filter_items_list": "Filter Home Page List",
//       "items_list_navigation": "Home List Navigation",
//       "items_list": "Home Content List",
//       "attributes": "Home Attributes",
//       "name_admin_bar": "Home Content",
//       "item_published": "Home Content Published",
//       "item_published_privately": "Home Content Published Privately",
//       "item_reverted_to_draft": "Home Content Reverted To Draft",
//       "item_scheduled": "Home Content Scheduled",
//       "item_updated": "Home Content Updated",
//       "parent_item_colon": "Parent Home Content"
//     },
//     "custom_supports": ""
//   },
//   "services_content": {
//     "name": "services_content",
//     "label": "Services_contents",
//     "singular_label": "Services_content",
//     "description": "Services content data",
//     "public": "true",
//     "publicly_queryable": "true",
//     "show_ui": "true",
//     "show_in_graphql":"true",
//     "hierarchical": "true",
//     "graphql_single_name":"Services_content",
//     "graphql_plural_name":"Services_contents",
//     "show_in_nav_menus": "true",
//     "delete_with_user": "false",
//     "show_in_rest": "true",
//     "rest_base": "Services_Page_Content",
//     "rest_controller_class": "",
//     "has_archive": "false",
//     "has_archive_string": "",
//     "exclude_from_search": "false",
//     "capability_type": "post",
//     "rewrite": "true",
//     "rewrite_slug": "",
//     "rewrite_withfront": "true",
//     "query_var": "true",
//     "query_var_slug": "",
//     "menu_position": "",
//     "show_in_menu": "true",
//     "show_in_menu_string": "",
//     "menu_icon": "dashicons-cloud",
//     "supports": [
//       "title",
//       "editor",
//       "thumbnail",
//       "excerpt",
//       "trackbacks",
//       "custom-fields",
//       "comments",
//       "revisions",
//       "author",
//       "page-attributes",
//       "post-formats",
//       "none"
//     ],
//     "taxonomies": ["category", "post_tag"],
//     "labels": {
//       "menu_name": "Services Page",
//       "all_items": "All Services",
//       "add_new": "Add New Service",
//       "add_new_item": "Add New Service",
//       "edit_item": "Edit Service",
//       "new_item": "New Service",
//       "view_item": "View Service",
//       "view_items": "View Services",
//       "search_items": "Search Services",
//       "not_found": "No Services Found",
//       "not_found_in_trash": "No Services Found In Trash",
//       "parent": "Parent Service",
//       "featured_image": "Featured image for this service",
//       "set_featured_image": "Set featured image for this service",
//       "remove_featured_image": "Remove featured image for this service",
//       "use_featured_image": "Use as featured image for this service",
//       "archives": "Services Archive",
//       "insert_into_item": "Insert into services page",
//       "uploaded_to_this_item": "Upload to the services page",
//       "filter_items_list": "Filter Services Page List",
//       "items_list_navigation": "Services List Navigation",
//       "items_list": "Service List",
//       "attributes": "Services Attributes",
//       "name_admin_bar": "Service",
//       "item_published": "Service Published",
//       "item_published_privately": "Service Published Privately",
//       "item_reverted_to_draft": "Service Reverted To Draft",
//       "item_scheduled": "Service Scheduled",
//       "item_updated": "Service Updated",
//       "parent_item_colon": "Parent Service"
//     },
//     "custom_supports": ""
//   },
//   "Promotions_content": {
//     "name": "Promotions_content",
//     "label": "Promotions_contents",
//     "singular_label": "Promotions_content",
//     "description": "Promotion content data",
//     "public": "true",
//     "publicly_queryable": "true",
//     "show_ui": "true",
//     "show_in_graphql":"true",
//     "hierarchical": "true",
//     "graphql_single_name":"Promotions_content",
//     "graphql_plural_name":"Promotions_contents",
//     "show_in_nav_menus": "true",
//     "delete_with_user": "false",
//     "show_in_rest": "true",
//     "rest_base": "Promotions_Page_Content",
//     "rest_controller_class": "",
//     "has_archive": "false",
//     "has_archive_string": "",
//     "exclude_from_search": "false",
//     "capability_type": "post",
//     "rewrite": "true",
//     "rewrite_slug": "",
//     "rewrite_withfront": "true",
//     "query_var": "true",
//     "query_var_slug": "",
//     "menu_position": "",
//     "show_in_menu": "true",
//     "show_in_menu_string": "",
//     "menu_icon": "dashicons-cloud",
//     "supports": [
//       "title",
//       "editor",
//       "thumbnail",
//       "excerpt",
//       "trackbacks",
//       "custom-fields",
//       "comments",
//       "revisions",
//       "author",
//       "page-attributes",
//       "post-formats",
//       "none"
//     ],
//     "taxonomies": ["category", "post_tag"],
//     "labels": {
//       "menu_name": "Promotion Page",
//       "all_items": "All Promotion Content",
//       "add_new": "Add New Promotions",
//       "add_new_item": "Add New Promotions",
//       "edit_item": "Edit Promotions",
//       "new_item": "New Promotions",
//       "view_item": "View Promotions",
//       "view_items": "View Promotion",
//       "search_items": "Search Promotion",
//       "not_found": "No Promotion Found",
//       "not_found_in_trash": "No Promotion Found In Trash",
//       "parent": "Parent Promotions",
//       "featured_image": "Featured Image For This Promotions",
//       "set_featured_image": "Set Featured Image For This Promotions",
//       "remove_featured_image": "Remove Featured Image For This Promotions",
//       "use_featured_image": "Use As Featured Image For This Promotions",
//       "archives": "Promotion Archive",
//       "insert_into_item": "Insert Into Promotion Page",
//       "uploaded_to_this_item": "Upload To The Promotion Page",
//       "filter_items_list": "Filter Promotion Page List",
//       "items_list_navigation": "Promotion List Navigation",
//       "items_list": "Promotions List",
//       "attributes": "Promotion Attributes",
//       "name_admin_bar": "Promotions",
//       "item_published": "Promotions Published",
//       "item_published_privately": "Promotions Published Privately",
//       "item_reverted_to_draft": "Promotions Reverted To Draft",
//       "item_scheduled": "Promotions Scheduled",
//       "item_updated": "Promotions Updated",
//       "parent_item_colon": "Parent Promotions"
//     },
//     "custom_supports": ""
//   },
//   "About_content": {
//     "name": "About_content",
//     "label": "About_contents",
//     "singular_label": "About_content",
//     "description": "About content data",
//     "public": "true",
//     "publicly_queryable": "true",
//     "show_ui": "true",
//     "show_in_graphql":"true",
//     "hierarchical": "true",
//     "graphql_single_name":"About_content",
//     "graphql_plural_name":"About_contents",
//     "show_in_nav_menus": "true",
//     "delete_with_user": "false",
//     "show_in_rest": "true",
//     "rest_base": "Contact_Page_Content",
//     "rest_controller_class": "",
//     "has_archive": "false",
//     "has_archive_string": "",
//     "exclude_from_search": "false",
//     "capability_type": "post",
//     "rewrite": "true",
//     "rewrite_slug": "",
//     "rewrite_withfront": "true",
//     "query_var": "true",
//     "query_var_slug": "",
//     "menu_position": "",
//     "show_in_menu": "true",
//     "show_in_menu_string": "",
//     "menu_icon": "dashicons-cloud",
//     "supports": [
//       "title",
//       "editor",
//       "thumbnail",
//       "excerpt",
//       "trackbacks",
//       "custom-fields",
//       "comments",
//       "revisions",
//       "author",
//       "page-attributes",
//       "post-formats",
//       "none"
//     ],
//     "taxonomies": ["category", "post_tag"],
//     "labels": {
//       "menu_name": "Why Cyberworks Page",
//       "all_items": "All About Content",
//       "add_new": "Add New About Content",
//       "add_new_item": "Add New About Content",
//       "edit_item": "Edit About Content",
//       "new_item": "New About Content",
//       "view_item": "View About Content",
//       "view_items": "View About",
//       "search_items": "Search About",
//       "not_found": "No About Found",
//       "not_found_in_trash": "No About Found In Trash",
//       "parent": "Parent About Content",
//       "featured_image": "Featured Image For This About Content",
//       "set_featured_image": "Set Featured Image For This About Content",
//       "remove_featured_image": "Remove Featured Image For This About Content",
//       "use_featured_image": "Use As Featured Image For This About Content",
//       "archives": "About Archive",
//       "insert_into_item": "Insert Into About Page",
//       "uploaded_to_this_item": "Upload To The About Page",
//       "filter_items_list": "Filter About Page List",
//       "items_list_navigation": "About List Navigation",
//       "items_list": "About Content List",
//       "attributes": "About Attributes",
//       "name_admin_bar": "About Content",
//       "item_published": "About Content Published",
//       "item_published_privately": "About Content Published Privately",
//       "item_reverted_to_draft": "About Content Reverted To Draft",
//       "item_scheduled": "About Content Scheduled",
//       "item_updated": "About Content Updated",
//       "parent_item_colon": "Parent About Content"
//     },
//     "custom_supports": ""
//   },
//   "Contact_content": {
//     "name": "Contact_content",
//     "label": "Contact_contents",
//     "singular_label": "Contact_content",
//     "description": "Contact content data",
//     "public": "true",
//     "publicly_queryable": "true",
//     "show_ui": "true",
//     "show_in_graphql":"true",
//     "hierarchical": "true",
//     "graphql_single_name":"Contact_content",
//     "graphql_plural_name":"Contact_contents",
//     "show_in_nav_menus": "true",
//     "delete_with_user": "false",
//     "show_in_rest": "true",
//     "rest_base": "Contact_Page_Content",
//     "rest_controller_class": "",
//     "has_archive": "false",
//     "has_archive_string": "",
//     "exclude_from_search": "false",
//     "capability_type": "post",
//     "rewrite": "true",
//     "rewrite_slug": "",
//     "rewrite_withfront": "true",
//     "query_var": "true",
//     "query_var_slug": "",
//     "menu_position": "",
//     "show_in_menu": "true",
//     "show_in_menu_string": "",
//     "menu_icon": "dashicons-cloud",
//     "supports": [
//       "title",
//       "editor",
//       "thumbnail",
//       "excerpt",
//       "trackbacks",
//       "custom-fields",
//       "comments",
//       "revisions",
//       "author",
//       "page-attributes",
//       "post-formats",
//       "none"
//     ],
//     "taxonomies": ["category", "post_tag"],
//     "labels": {
//       "menu_name": "Contact Page",
//       "all_items": "All Contact Content",
//       "add_new": "Add New Contact Content",
//       "add_new_item": "Add New Contact Content",
//       "edit_item": "Edit Contact Content",
//       "new_item": "New Contact Content",
//       "view_item": "View Contact Content",
//       "view_items": "View Contact",
//       "search_items": "Search Contact",
//       "not_found": "No Contact Found",
//       "not_found_in_trash": "No Contact Found In Trash",
//       "parent": "Parent Contact Content",
//       "featured_image": "Featured Image For This Contact Content",
//       "set_featured_image": "Set Featured Image For This Contact Content",
//       "remove_featured_image": "Remove Featured Image For This Contact Content",
//       "use_featured_image": "Use As Featured Image For This Contact Content",
//       "archives": "Contact Archive",
//       "insert_into_item": "Insert Into Contact Page",
//       "uploaded_to_this_item": "Upload To The Contact Page",
//       "filter_items_list": "Filter Contact Page List",
//       "items_list_navigation": "Contact List Navigation",
//       "items_list": "Contact Content List",
//       "attributes": "Contact Attributes",
//       "name_admin_bar": "Contact Content",
//       "item_published": "Contact Content Published",
//       "item_published_privately": "Contact Content Published Privately",
//       "item_reverted_to_draft": "Contact Content Reverted To Draft",
//       "item_scheduled": "Contact Content Scheduled",
//       "item_updated": "Contact Content Updated",
//       "parent_item_colon": "Parent Contact Content"
//     },
//     "custom_supports": ""
//   },
//   "Footer_content": {
//     "name": "Footer_content",
//     "label": "Footer_contents",
//     "singular_label": "Footer_content",
//     "description": "Footer content data",
//     "public": "true",
//     "publicly_queryable": "true",
//     "show_ui": "true",
//     "show_in_graphql":"true",
//     "hierarchical": "true",
//     "graphql_single_name":"Footer_content",
//     "graphql_plural_name":"Footer_contents",
//     "show_in_nav_menus": "true",
//     "delete_with_user": "false",
//     "show_in_rest": "true",
//     "rest_base": "Footer_Page_Content",
//     "rest_controller_class": "",
//     "has_archive": "false",
//     "has_archive_string": "",
//     "exclude_from_search": "false",
//     "capability_type": "post",
//     "rewrite": "true",
//     "rewrite_slug": "",
//     "rewrite_withfront": "true",
//     "query_var": "true",
//     "query_var_slug": "",
//     "menu_position": "",
//     "show_in_menu": "true",
//     "show_in_menu_string": "",
//     "menu_icon": "dashicons-cloud",
//     "supports": [
//       "title",
//       "editor",
//       "thumbnail",
//       "excerpt",
//       "trackbacks",
//       "custom-fields",
//       "comments",
//       "revisions",
//       "author",
//       "page-attributes",
//       "post-formats",
//       "none"
//     ],
//     "taxonomies": ["category", "post_tag"],
//     "labels": {
//       "menu_name": "Footer Page",
//       "all_items": "All Footer Content",
//       "add_new": "Add New Footer Content",
//       "add_new_item": "Add New Footer Content",
//       "edit_item": "Edit Footer Content",
//       "new_item": "New Footer Content",
//       "view_item": "View Footer Content",
//       "view_items": "View Footer",
//       "search_items": "Search Footer",
//       "not_found": "No Footer Found",
//       "not_found_in_trash": "No Footer Found In Trash",
//       "parent": "Parent Footer Content",
//       "featured_image": "Featured Image For This Footer Content",
//       "set_featured_image": "Set Featured Image For This Footer Content",
//       "remove_featured_image": "Remove Featured Image For This Footer Content",
//       "use_featured_image": "Use As Featured Image For This Footer Content",
//       "archives": "Footer Archive",
//       "insert_into_item": "Insert Into Footer Page",
//       "uploaded_to_this_item": "Upload To The Footer Page",
//       "filter_items_list": "Filter Footer Page List",
//       "items_list_navigation": "Footer List Navigation",
//       "items_list": "Footer Content List",
//       "attributes": "Footer Attributes",
//       "name_admin_bar": "Footer Content","item_published":"Footer Content Published","item_published_privately":"Footer Content Published Privately","item_reverted_to_draft":"Footer Content Reverted To Draft","item_scheduled": "Footer Content Scheduled","item_updated":"Footer Content Updated","parent_item_colon":"Parent Footer Content"},"custom_supports":""}}

// Ex1_content: {
//   name: "Ex1_content",
//   label: "Ex1_contents",
//   singular_label: "Ex1_content",
//   description: "Ex2 content data",
//   public: "true",
//   publicly_queryable: "true",
//   show_ui: "true",
//   show_in_nav_menus: "true",
//   delete_with_user: "false",
//   show_in_rest: "true",
//   rest_base: "Ex1_Page_Content",
//   rest_controller_class: "",
//   has_archive: "false",
//   has_archive_string: "",
//   exclude_from_search: "false",
//   capability_type: "post",
//   hierarchical: "false",
//   rewrite: "true",
//   rewrite_slug: "",
//   rewrite_withfront: "true",
//   query_var: "true",
//   query_var_slug: "",
//   menu_position: "",
//   show_in_menu: "true",
//   show_in_menu_string: "",
//   menu_icon: "dashicons-cloud",
//   supports: [
//     "title",
//     "editor",
//     "thumbnail",
//     "excerpt",
//     "trackbacks",
//     "custom-fields",
//     "comments",
//     "revisions",
//     "author",
//     "page-attributes",
//     "post-formats",
//     "none",
//   ],
//   taxonomies: ["category", "post_tag"],
//   labels: {
//     menu_name: "Ex2 Page",
//     all_items: "All Ex2 Content",
//     add_new: "Add New Ex3",
//     add_new_item: "Add New Ex3",
//     edit_item: "Edit Ex3",
//     new_item: "New Ex3",
//     view_item: "View Ex3",
//     view_items: "View Ex2",
//     search_items: "Search Ex2",
//     not_found: "No Ex2 Found",
//     not_found_in_trash: "No Ex2 Found In Trash",
//     parent: "Parent Ex3",
//     featured_image: "Featured Image For This Ex3",
//     set_featured_image: "Set Featured Image For This Ex3",
//     remove_featured_image: "Remove Featured Image For This Ex3",
//     use_featured_image: "Use As Featured Image For This Ex3",
//     archives: "Ex2 Archive",
//     insert_into_item: "Insert Into Ex2 Page",
//     uploaded_to_this_item: "Upload To The Ex2 Page",
//     filter_items_list: "Filter Ex2 Page List",
//     items_list_navigation: "Ex2 List Navigation",
//     items_list: "Ex3 List",
//     attributes: "Ex2 Attributes",
//     name_admin_bar: "Ex3",
//     item_published: "Ex3 Published",
//     item_published_privately: "Ex3 Published Privately",
//     item_reverted_to_draft: "Ex3 Reverted To Draft",
//     item_scheduled: "Ex3 Scheduled",
//     item_updated: "Ex3 Updated",
//     parent_item_colon: "Parent Ex3",
//   },
//   custom_supports: "",
// },
